---
title: "Nature and Frequency of Job Changes - CPS"
author: "Axelle Clochard"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output:
  html_document:
  toc: true
toc_depth: 3
css: memostyle.css
---
  

  
``` {r WorkspaceSetup, include = FALSE} 


# ------------------------------------------------------------------------------------------------------#
# STEP 0. SET UP WORKSPACE AND PREPARE DATA FOR Analysis
# ------------------------------------------------------------------------------------------------------#
rm(list = ls())

# Set working directory 
setwd('C:/Users/axell/OneDrive/Documents/MIT/J-WEL/Job Distance')

# Load packages 
packages <- c("knitr",
              "ggplot2",
              "scales",
              "plyr",
              "dplyr",
              "tidyr",
              "gridExtra",
              "grid",
              "readxl",
              "stringr",
              "reshape2", 
              "kableExtra",
              "stargazer", 
              "Hmisc", 
              "caret", 
              "ipumsr",
              "R.utils",
              "sandwich",
              "lmtest",
              "htmltab")

lapply(packages, require, character.only = TRUE)
options(scipen = 999)
knitr::opts_chunk$set(echo = TRUE, fig.pos= "H")


# Set the latex engine path
Sys.setenv(PATH = paste(Sys.getenv("PATH"), "C:\\Users\\axell\\AppData\\Local\\MiKTeX\\2.9\\miktex\\bin\\x64", sep=.Platform$path.sep))
knitr::opts_chunk$set(fig.pos = 'H')
```


```{r include = FALSE}
# ------------------------------------------------------------------------------------------------------#
# STEP 1. IMPORT DATA
# ------------------------------------------------------------------------------------------------------#

### Read in CPS Data
ddi <- read_ipums_ddi("cps_00003.xml")
cps <- read_ipums_micro(ddi, data_file = "cps_00003.dat.gz", verbose = FALSE)

cps$CPSID <- as.character(cps$CPSID)
cps$CPSIDP <- as.character(cps$CPSIDP)

# Keep only respondants from 2011-2019 who are part of the ASEC and in the Labor force in the current year 
cps  <- subset(cps, ASECFLAG %in% c(1, 2) &  LABFORCE == 2) %>%
         subset(., YEAR %in% c(2011:2019))

# Create an ID variable to account for ASEC oversample
cps <- cps %>% mutate(ID = ifelse(CPSIDP == "0", paste0(YEAR, "ASEC", 1:n()), CPSIDP))


# subset to people who had jobs both years
cps$OCC <- as.numeric(as.character(cps$OCC))
cps$OCCLY <- as.numeric(as.character(cps$OCCLY))

cps$OCC[cps$OCC == 0] <- NA
cps$OCCLY[cps$OCCLY == 0] <- NA 

cps <- subset(cps, !is.na(OCC) & !is.na(OCCLY))




### Read in Occupational Information 
occ <- read.csv("OCC Codes 2011-2019.csv")
occ$OccupationDescription_LY <- occ$OccupationDescription

cps <- merge(x = cps, y = occ[c("OCC", "OccupationDescription")], by = "OCC", all.x = T) %>%
       merge(x = .,   y = occ[c("OCC", "OccupationDescription_LY")], by.x = "OCCLY", by.y = "OCC", all.x = T)

# Import the SOC/O*Net and CPS/SOC xwalks from https://www.bls.gov/emp/documentation/crosswalks.htm
xwalk = merge(x = read_excel("./nem-occcode-cps-crosswalk.xlsx", skip = 4)[c(2,4:5)],
              y = read_excel("./nem-onet-to-soc-crosswalk.xlsx", skip = 4)[c(2,4)],
              by.x = "Hybrid SOC Code", 
              by.y = "SOC Code", 
              all = T) 
names(xwalk) <- c( "HSOC_OCC", "CPS_OCC", "CPS_Title", "ONET10_SOC_OCC")


# Import the SOC/O*Net and CPS/SOC xwalks from https://www.onetcenter.org/taxonomy/2010/soc2018.html
xwalk = merge(x = xwalk,
              y = read_excel("./2010_to_2018_SOC_Crosswalk.xlsx", skip = 3)[c(1,3:4)],
              by.x = "ONET10_SOC_OCC", 
              by.y = "O*NET-SOC 2010 Code", 
              all = T) 

names(xwalk)[5:6] <- c("ONET18_SOC", "ONET18_Title")
xwalk <- distinct(xwalk, CPS_OCC, ONET18_SOC, .keep_all = T)

# Create SOC-Level flag
xwalk$SOCLvl <- ifelse(str_sub(as.character(xwalk$ONET10_SOC_OCC), -2, -1) == "00", 1, 0)
xwalk$ONET10_SOC <- substring(as.character(xwalk$ONET10_SOC_OCC), 1, 7)

xwalk_simp <- distinct(xwalk, CPS_OCC, ONET18_SOC, .keep_all = T) %>% 
              subset(., select = -c(HSOC_OCC, ONET10_SOC_OCC))


```




```{r include = FALSE}

# ------------------------------------------------------------------------------------------------------#
# STEP 2. AGGREGATE ALL CURRENT YEAR AND LAST YEAR JOB COMBINATIONS
# ------------------------------------------------------------------------------------------------------#

# Aggregate all combinations using CPS OCC Codes
jc <- cps %>% 
      group_by(OCC, OCCLY) %>%
      summarise(count = sum(ASECWT))

# Merge on ONET codes all  
jc <- merge(x = jc,
            y = subset(xwalk_simp, select =-c(SOCLvl)),
            by.x = "OCC", by.y = "CPS_OCC", 
            all.x = T) 

jc <- merge(x = jc,
            y = subset(xwalk_simp, select =-c(SOCLvl)),
            by.x = "OCCLY", by.y = "CPS_OCC", 
            suffixes = c("","_LY"),
            all.x = T)


# Adjust weights to account for multiple matches in xwalks
jc <- merge(x = subset(jc, select = -c(CPS_Title, ONET10_SOC, ONET10_SOC_LY, CPS_Title_LY)),
            y = jc %>% group_by(OCC, OCCLY) %>%
                summarise(n = n()),
            by = c('OCC', 'OCCLY'), all = T) %>%
       mutate(., count = as.numeric(as.character(count))/n)
```



```{r include = FALSE}

# ------------------------------------------------------------------------------------------------------#
# STEP 3a. CALCULATE JOB COMBINATION FREQUENCY: Overall and by Title
# ------------------------------------------------------------------------------------------------------#
j1 <- jc
total = sum(j1$count)
j1 <- j1 %>% mutate(pct_tot = (count/total)*100)

j1 <- j1 %>% 
      group_by(ONET18_SOC_LY) %>%
      mutate(count_socly = sum(count))

j1$pct_socly <- (j1$count/j1$count_socly)*100

# ------------------------------------------------------------------------------------------------------#
# STEP 3b. CATEGORIZE JOB CHANGE TYPES
# ------------------------------------------------------------------------------------------------------#

j1 <- j1 %>%
      mutate(same = ifelse(ONET18_SOC == ONET18_SOC_LY, 1, 0), # Does this artificially create job changes? In theory, we can't rule those out. 
             in_grp = ifelse(substring(ONET18_SOC, 1, 2) == substring(ONET18_SOC_LY, 1, 2), 1, 0),
             in_minor_grp = ifelse(substring(ONET18_SOC, 1, 5) == substring(ONET18_SOC_LY, 1, 5), 1, 0),
             in_broad_occ = ifelse(substring(ONET18_SOC, 1, 6) == substring(ONET18_SOC_LY, 1, 6), 1, 0))


write.csv(x=j1, file="JobCY_LY_2011to19.csv",  row.names = FALSE)
```




```{r include = FALSE}

# ------------------------------------------------------------------------------------------------------#
# STEP 4a. FOR CHANGES ONLY: CALCULATE JOB CHANGE FREQUENCY: Overall and by Title
# ------------------------------------------------------------------------------------------------------#

j2 <- subset(jc, OCC != OCCLY) 

total = sum(j2$count)
j2 <- j2 %>% mutate(pct_tot = (count/total)*100)

j2 <- j2 %>% 
      group_by(ONET18_SOC_LY) %>%
      mutate(count_socly = sum(count)) %>%
      subset(., select =-c(n))

j2$pct_socly <- (j2$count/j2$count_socly)*100

# ------------------------------------------------------------------------------------------------------#
# STEP 4b.  FOR CHANGES ONLY: CATEGORIZE JOB CHANGE TYPES
# ------------------------------------------------------------------------------------------------------#

j2 <- j2 %>%
      mutate(in_grp = ifelse(substring(ONET18_SOC, 1, 2) == substring(ONET18_SOC_LY, 1, 2), 1, 0),
             in_minor_grp = ifelse(substring(ONET18_SOC, 1, 5) == substring(ONET18_SOC_LY, 1, 5), 1, 0),
             in_broad_occ = ifelse(substring(ONET18_SOC, 1, 6) == substring(ONET18_SOC_LY, 1, 6), 1, 0))

j2 <- j2[c("ONET18_SOC", "ONET18_SOC_LY", "ONET18_Title", "ONET18_Title_LY", "count", "pct_tot", "count_socly", "pct_socly", "in_grp", "in_minor_grp", "in_broad_occ")]

write.csv(x=j2, file="JobChanges_2011to19.csv",  row.names = FALSE)


```

to do

ADD IN THE STAYERS
hOW MATCHED
HOW DIFFERENTS P-VALYE
